# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'
    - run: npm ci
    - run: npm run build-prod
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifact
        path: dist
        retention-days: 1

  deploy:
    needs: build
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist
      - name: Inject DB credentials
        run: |
          sed -i 's/$UserDB = ".*"/$UserDB = "${{ secrets.DB_USER }}"/g' ./dist/sound-book/api/classes/_class.db.php
          sed -i 's/$BaseDB = ".*"/$BaseDB = "${{ secrets.DB_USER }}"/g' ./dist/sound-book/api/classes/_class.db.php
          sed -i 's/$PassDB = ".*";/$PassDB = "${{ secrets.DB_PASSWORD }}";/g' ./dist/sound-book/api/classes/_class.db.php
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist/sound-book/'
          dangerous-clean-slate: true
          exclude: |
            **/api/tmp/**